# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/takayuki/Desktop/program/python/Spyder_workspcae/PyQt_test/ui/PyQt_test/mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(500, 400)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(500, 400))
        MainWindow.setMaximumSize(QtCore.QSize(5000, 5000))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.treeView_PlanetAttribute = AttributeView(self.centralWidget)
        self.treeView_PlanetAttribute.setObjectName(_fromUtf8("treeView_PlanetAttribute"))
        self.verticalLayout_2.addWidget(self.treeView_PlanetAttribute)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_AddPlanet = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_AddPlanet.sizePolicy().hasHeightForWidth())
        self.pushButton_AddPlanet.setSizePolicy(sizePolicy)
        self.pushButton_AddPlanet.setObjectName(_fromUtf8("pushButton_AddPlanet"))
        self.horizontalLayout_2.addWidget(self.pushButton_AddPlanet)
        self.pushButton_DeletePlanet = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_DeletePlanet.sizePolicy().hasHeightForWidth())
        self.pushButton_DeletePlanet.setSizePolicy(sizePolicy)
        self.pushButton_DeletePlanet.setObjectName(_fromUtf8("pushButton_DeletePlanet"))
        self.horizontalLayout_2.addWidget(self.pushButton_DeletePlanet)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout_3.setMargin(11)
        self.formLayout_3.setSpacing(6)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_GRV = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_GRV.sizePolicy().hasHeightForWidth())
        self.label_GRV.setSizePolicy(sizePolicy)
        self.label_GRV.setObjectName(_fromUtf8("label_GRV"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_GRV)
        self.lineEdit_G = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_G.setBaseSize(QtCore.QSize(0, 0))
        self.lineEdit_G.setAcceptDrops(False)
        self.lineEdit_G.setObjectName(_fromUtf8("lineEdit_G"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_G)
        self.verticalLayout_2.addLayout(self.formLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout.setMargin(11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lineEdit_TimeIncrement = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_TimeIncrement.setObjectName(_fromUtf8("lineEdit_TimeIncrement"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_TimeIncrement)
        self.lineEdit_StopTime = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_StopTime.setObjectName(_fromUtf8("lineEdit_StopTime"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_StopTime)
        self.label_timeincrement = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_timeincrement.sizePolicy().hasHeightForWidth())
        self.label_timeincrement.setSizePolicy(sizePolicy)
        self.label_timeincrement.setObjectName(_fromUtf8("label_timeincrement"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_timeincrement)
        self.label_stoptime = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_stoptime.sizePolicy().hasHeightForWidth())
        self.label_stoptime.setSizePolicy(sizePolicy)
        self.label_stoptime.setObjectName(_fromUtf8("label_stoptime"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_stoptime)
        self.horizontalLayout.addLayout(self.formLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setMargin(11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.comboBox_Choose2Dor3D = QtGui.QComboBox(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Choose2Dor3D.sizePolicy().hasHeightForWidth())
        self.comboBox_Choose2Dor3D.setSizePolicy(sizePolicy)
        self.comboBox_Choose2Dor3D.setObjectName(_fromUtf8("comboBox_Choose2Dor3D"))
        self.comboBox_Choose2Dor3D.addItem(_fromUtf8(""))
        self.comboBox_Choose2Dor3D.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_Choose2Dor3D)
        self.pushButton_Calc = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Calc.sizePolicy().hasHeightForWidth())
        self.pushButton_Calc.setSizePolicy(sizePolicy)
        self.pushButton_Calc.setObjectName(_fromUtf8("pushButton_Calc"))
        self.verticalLayout_3.addWidget(self.pushButton_Calc)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 500, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuKepler = QtGui.QMenu(self.menuBar)
        self.menuKepler.setObjectName(_fromUtf8("menuKepler"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuLoad = QtGui.QMenu(self.menuFile)
        self.menuLoad.setObjectName(_fromUtf8("menuLoad"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuTools = QtGui.QMenu(self.menuBar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionAbout_Kepler = QtGui.QAction(MainWindow)
        self.actionAbout_Kepler.setObjectName(_fromUtf8("actionAbout_Kepler"))
        self.actionPreference = QtGui.QAction(MainWindow)
        self.actionPreference.setObjectName(_fromUtf8("actionPreference"))
        self.actionExport = QtGui.QAction(MainWindow)
        self.actionExport.setObjectName(_fromUtf8("actionExport"))
        self.actionHow_to_use = QtGui.QAction(MainWindow)
        self.actionHow_to_use.setObjectName(_fromUtf8("actionHow_to_use"))
        self.actionHow_does_this_work = QtGui.QAction(MainWindow)
        self.actionHow_does_this_work.setObjectName(_fromUtf8("actionHow_does_this_work"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionLoad_SOL = QtGui.QAction(MainWindow)
        self.actionLoad_SOL.setObjectName(_fromUtf8("actionLoad_SOL"))
        self.actionLoad_SOL_3D = QtGui.QAction(MainWindow)
        self.actionLoad_SOL_3D.setObjectName(_fromUtf8("actionLoad_SOL_3D"))
        self.actionLoad_your_settings = QtGui.QAction(MainWindow)
        self.actionLoad_your_settings.setObjectName(_fromUtf8("actionLoad_your_settings"))
        self.actionViewer = QtGui.QAction(MainWindow)
        self.actionViewer.setObjectName(_fromUtf8("actionViewer"))
        self.actionTable_Viewer = QtGui.QAction(MainWindow)
        self.actionTable_Viewer.setObjectName(_fromUtf8("actionTable_Viewer"))
        self.menuKepler.addAction(self.actionAbout_Kepler)
        self.menuLoad.addAction(self.actionLoad_your_settings)
        self.menuLoad.addAction(self.actionLoad_SOL)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.menuLoad.menuAction())
        self.menuHelp.addAction(self.actionHow_to_use)
        self.menuHelp.addAction(self.actionHow_does_this_work)
        self.menuTools.addAction(self.actionViewer)
        self.menuTools.addAction(self.actionTable_Viewer)
        self.menuBar.addAction(self.menuKepler.menuAction())
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButton_AddPlanet.setText(_translate("MainWindow", "Add Planet", None))
        self.pushButton_DeletePlanet.setText(_translate("MainWindow", "Delete Planet", None))
        self.label_GRV.setText(_translate("MainWindow", "G (gravitational constant) [CODATA RV: 6.674e-11]", None))
        self.label_timeincrement.setText(_translate("MainWindow", "Time Increment", None))
        self.label_stoptime.setText(_translate("MainWindow", "Stop Time", None))
        self.comboBox_Choose2Dor3D.setItemText(0, _translate("MainWindow", "2D", None))
        self.comboBox_Choose2Dor3D.setItemText(1, _translate("MainWindow", "3D", None))
        self.pushButton_Calc.setText(_translate("MainWindow", "Calculate", None))
        self.menuKepler.setTitle(_translate("MainWindow", "Kepler", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuLoad.setTitle(_translate("MainWindow", "Load", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionAbout_Kepler.setText(_translate("MainWindow", "About Kepler", None))
        self.actionPreference.setText(_translate("MainWindow", "Preferences", None))
        self.actionExport.setText(_translate("MainWindow", "Export", None))
        self.actionHow_to_use.setText(_translate("MainWindow", "How to use", None))
        self.actionHow_does_this_work.setText(_translate("MainWindow", "How does this work?", None))
        self.actionSave_as.setText(_translate("MainWindow", "Save as...", None))
        self.actionLoad_SOL.setText(_translate("MainWindow", "Load SOL", None))
        self.actionLoad_SOL_3D.setText(_translate("MainWindow", "Load SOL (3D)", None))
        self.actionLoad_your_settings.setText(_translate("MainWindow", "Load your settings", None))
        self.actionViewer.setText(_translate("MainWindow", "Viewer", None))
        self.actionTable_Viewer.setText(_translate("MainWindow", "Table Viewer", None))

class AttributeView(QtGui.QTreeView):
    def __init__(self, parent=None):
        super(AttributeView, self).__init__(parent)
        self.setItemsExpandable(False)
        self.setIndentation(0)
        self.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)

    def drawBranches(self, painter, rect, index):
        return
