# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/takayuki/Desktop/program/python/Spyder_workspcae/PyQt_test/ui/PyQt_test/pgviewer.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import pyqtgraph as pg

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PGViewer(object):
    def setupUi(self, PGViewer):
        PGViewer.setObjectName(_fromUtf8("PGViewer"))
        PGViewer.resize(640, 480)
        self.centralwidget = QtGui.QWidget(PGViewer)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.treeView_PlanetAttribute = QtGui.QTreeView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView_PlanetAttribute.sizePolicy().hasHeightForWidth())
        self.treeView_PlanetAttribute.setSizePolicy(sizePolicy)
        self.treeView_PlanetAttribute.setMinimumSize(QtCore.QSize(100, 200))
        self.treeView_PlanetAttribute.setMaximumSize(QtCore.QSize(200, 16777215))
        self.treeView_PlanetAttribute.setObjectName(_fromUtf8("treeView_PlanetAttribute"))
        self.horizontalLayout.addWidget(self.treeView_PlanetAttribute)
        self.widget_plot = pg.GraphicsLayoutWidget(self.centralwidget)#QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_plot.sizePolicy().hasHeightForWidth())
        self.widget_plot.setSizePolicy(sizePolicy)
        self.widget_plot.setMinimumSize(QtCore.QSize(200, 200))
        self.widget_plot.setObjectName(_fromUtf8("widget_plot"))
        self.horizontalLayout.addWidget(self.widget_plot)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.radioButton_AutoRun = QtGui.QRadioButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_AutoRun.sizePolicy().hasHeightForWidth())
        self.radioButton_AutoRun.setSizePolicy(sizePolicy)
        self.radioButton_AutoRun.setObjectName(_fromUtf8("radioButton_AutoRun"))
        self.horizontalLayout_3.addWidget(self.radioButton_AutoRun)
        self.lineEdit_Start_Time = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Start_Time.sizePolicy().hasHeightForWidth())
        self.lineEdit_Start_Time.setSizePolicy(sizePolicy)
        self.lineEdit_Start_Time.setMaximumSize(QtCore.QSize(16777215, 16777215))
        #self.lineEdit_Start_Time.setClearButtonEnabled(False)
        self.lineEdit_Start_Time.setObjectName(_fromUtf8("lineEdit_Start_Time"))
        self.horizontalLayout_3.addWidget(self.lineEdit_Start_Time)
        self.label_to = QtGui.QLabel(self.centralwidget)
        self.label_to.setObjectName(_fromUtf8("label_to"))
        self.horizontalLayout_3.addWidget(self.label_to)
        self.lineEdit_EndTime = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_EndTime.sizePolicy().hasHeightForWidth())
        self.lineEdit_EndTime.setSizePolicy(sizePolicy)
        self.lineEdit_EndTime.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_EndTime.setObjectName(_fromUtf8("lineEdit_EndTime"))
        self.horizontalLayout_3.addWidget(self.lineEdit_EndTime)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_RefreshRate = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_RefreshRate.sizePolicy().hasHeightForWidth())
        self.label_RefreshRate.setSizePolicy(sizePolicy)
        self.label_RefreshRate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RefreshRate.setObjectName(_fromUtf8("label_RefreshRate"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_RefreshRate)
        self.label_Time = QtGui.QLabel(self.centralwidget)
        self.label_Time.setObjectName(_fromUtf8("label_Time"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_Time)
        self.lineEdit_Time = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Time.sizePolicy().hasHeightForWidth())
        self.lineEdit_Time.setSizePolicy(sizePolicy)
        self.lineEdit_Time.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_Time.setObjectName(_fromUtf8("lineEdit_Time"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_Time)
        self.lineEdit_RefreshRate = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_RefreshRate.sizePolicy().hasHeightForWidth())
        self.lineEdit_RefreshRate.setSizePolicy(sizePolicy)
        self.lineEdit_RefreshRate.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_RefreshRate.setObjectName(_fromUtf8("lineEdit_RefreshRate"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_RefreshRate)
        self.horizontalLayout_3.addLayout(self.formLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        PGViewer.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(PGViewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuViewer = QtGui.QMenu(self.menubar)
        self.menuViewer.setObjectName(_fromUtf8("menuViewer"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        PGViewer.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(PGViewer)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        PGViewer.setStatusBar(self.statusbar)
        self.actionAbout_Kepler_Viewer = QtGui.QAction(PGViewer)
        self.actionAbout_Kepler_Viewer.setObjectName(_fromUtf8("actionAbout_Kepler_Viewer"))
        self.actionSave = QtGui.QAction(PGViewer)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionLoad = QtGui.QAction(PGViewer)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionSave_Image = QtGui.QAction(PGViewer)
        self.actionSave_Image.setObjectName(_fromUtf8("actionSave_Image"))
        self.menuViewer.addAction(self.actionAbout_Kepler_Viewer)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_Image)
        self.menuFile.addAction(self.actionLoad)
        self.menubar.addAction(self.menuViewer.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(PGViewer)
        QtCore.QMetaObject.connectSlotsByName(PGViewer)

    def retranslateUi(self, PGViewer):
        PGViewer.setWindowTitle(_translate("PGViewer", "MainWindow", None))
        self.radioButton_AutoRun.setText(_translate("PGViewer", "Run", None))
        self.label_to.setText(_translate("PGViewer", "to", None))
        self.label_RefreshRate.setText(_translate("PGViewer", "Refresh Rate:", None))
        self.label_Time.setText(_translate("PGViewer", "Time:", None))
        self.menuViewer.setTitle(_translate("PGViewer", "Viewer", None))
        self.menuFile.setTitle(_translate("PGViewer", "File", None))
        self.actionAbout_Kepler_Viewer.setText(_translate("PGViewer", "About Kepler Viewer", None))
        self.actionSave.setText(_translate("PGViewer", "Save", None))
        self.actionLoad.setText(_translate("PGViewer", "Load", None))
        self.actionSave_Image.setText(_translate("PGViewer", "Save Image", None))

