# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/takayuki/Desktop/program/python/Spyder_workspcae/PyQt_test/ui/PyQt_test/viewer.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import pyqtgraph as pg

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Viewer(object):
    def setupUi(self, Viewer):
        Viewer.setObjectName(_fromUtf8("Viewer"))
        Viewer.resize(500, 400)
        self.centralwidget = QtGui.QWidget(Viewer)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.treeView_PlanetAttribute = QtGui.QTreeView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView_PlanetAttribute.sizePolicy().hasHeightForWidth())
        self.treeView_PlanetAttribute.setSizePolicy(sizePolicy)
        self.treeView_PlanetAttribute.setMinimumSize(QtCore.QSize(100, 200))
        self.treeView_PlanetAttribute.setMaximumSize(QtCore.QSize(200, 16777215))
        self.treeView_PlanetAttribute.setObjectName(_fromUtf8("treeView_PlanetAttribute"))
        self.horizontalLayout.addWidget(self.treeView_PlanetAttribute)
        
        self.widget_mpl = pg.GraphicsLayoutWidget(self.centralwidget)#QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_mpl.sizePolicy().hasHeightForWidth())
        self.widget_mpl.setSizePolicy(sizePolicy)
        self.widget_mpl.setMinimumSize(QtCore.QSize(200, 200))
        self.widget_mpl.setObjectName(_fromUtf8("widget_mpl"))
        self.horizontalLayout.addWidget(self.widget_mpl)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkBox_AutoRun = QtGui.QCheckBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_AutoRun.sizePolicy().hasHeightForWidth())
        self.checkBox_AutoRun.setSizePolicy(sizePolicy)
        self.checkBox_AutoRun.setObjectName(_fromUtf8("checkBox_AutoRun"))
        self.horizontalLayout_3.addWidget(self.checkBox_AutoRun)
        self.lineEdit_Start_Time = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Start_Time.sizePolicy().hasHeightForWidth())
        self.lineEdit_Start_Time.setSizePolicy(sizePolicy)
        self.lineEdit_Start_Time.setMaximumSize(QtCore.QSize(16777215, 16777215))
        #self.lineEdit_Start_Time.setClearButtonEnabled(False)
        self.lineEdit_Start_Time.setObjectName(_fromUtf8("lineEdit_Start_Time"))
        self.horizontalLayout_3.addWidget(self.lineEdit_Start_Time)
        self.label_to = QtGui.QLabel(self.centralwidget)
        self.label_to.setObjectName(_fromUtf8("label_to"))
        self.horizontalLayout_3.addWidget(self.label_to)
        self.lineEdit_EndTime = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_EndTime.sizePolicy().hasHeightForWidth())
        self.lineEdit_EndTime.setSizePolicy(sizePolicy)
        self.lineEdit_EndTime.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_EndTime.setObjectName(_fromUtf8("lineEdit_EndTime"))
        self.horizontalLayout_3.addWidget(self.lineEdit_EndTime)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_RefreshRate = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_RefreshRate.sizePolicy().hasHeightForWidth())
        self.label_RefreshRate.setSizePolicy(sizePolicy)
        self.label_RefreshRate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RefreshRate.setObjectName(_fromUtf8("label_RefreshRate"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_RefreshRate)
        self.lineEdit_RefreshRate = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_RefreshRate.sizePolicy().hasHeightForWidth())
        self.lineEdit_RefreshRate.setSizePolicy(sizePolicy)
        self.lineEdit_RefreshRate.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_RefreshRate.setObjectName(_fromUtf8("lineEdit_RefreshRate"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_RefreshRate)
        self.horizontalLayout_3.addLayout(self.formLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalSlider_Time = QtGui.QSlider(self.centralwidget)
        self.horizontalSlider_Time.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Time.setObjectName(_fromUtf8("horizontalSlider_Time"))
        self.horizontalLayout_2.addWidget(self.horizontalSlider_Time)
        self.lineEdit_Time = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Time.sizePolicy().hasHeightForWidth())
        self.lineEdit_Time.setSizePolicy(sizePolicy)
        self.lineEdit_Time.setObjectName(_fromUtf8("lineEdit_Time"))
        self.horizontalLayout_2.addWidget(self.lineEdit_Time)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        Viewer.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Viewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuViewer = QtGui.QMenu(self.menubar)
        self.menuViewer.setObjectName(_fromUtf8("menuViewer"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        Viewer.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Viewer)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Viewer.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(Viewer)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_as = QtGui.QAction(Viewer)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionLoad = QtGui.QAction(Viewer)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionAbout_Viewer = QtGui.QAction(Viewer)
        self.actionAbout_Viewer.setObjectName(_fromUtf8("actionAbout_Viewer"))
        self.actionExport = QtGui.QAction(Viewer)
        self.actionExport.setObjectName(_fromUtf8("actionExport"))
        self.actionTable_Viewer = QtGui.QAction(Viewer)
        self.actionTable_Viewer.setObjectName(_fromUtf8("actionTable_Viewer"))
        self.actionSave_Image = QtGui.QAction(Viewer)
        self.actionSave_Image.setObjectName(_fromUtf8("actionSave_Image"))
        self.menuViewer.addAction(self.actionAbout_Viewer)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave_Image)
        self.menubar.addAction(self.menuViewer.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(Viewer)
        QtCore.QMetaObject.connectSlotsByName(Viewer)

    def retranslateUi(self, Viewer):
        Viewer.setWindowTitle(_translate("Viewer", "MainWindow", None))
        self.checkBox_AutoRun.setText(_translate("Viewer", "Auto Run", None))
        self.label_to.setText(_translate("Viewer", ":", None))
        self.label_RefreshRate.setText(_translate("Viewer", "Refresh Rate:", None))
        self.menuViewer.setTitle(_translate("Viewer", "Viewer", None))
        self.menuFile.setTitle(_translate("Viewer", "File", None))
        self.actionSave.setText(_translate("Viewer", "Save", None))
        self.actionSave_as.setText(_translate("Viewer", "Save as...", None))
        self.actionLoad.setText(_translate("Viewer", "Load", None))
        self.actionAbout_Viewer.setText(_translate("Viewer", "About Viewer", None))
        self.actionExport.setText(_translate("Viewer", "Export", None))
        self.actionTable_Viewer.setText(_translate("Viewer", "Table Viewer", None))
        self.actionSave_Image.setText(_translate("Viewer", "Save Image", None))

