# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/takayuki/Desktop/program/python/Spyder_workspcae/PyQt_test/ui/PyQt_test/ViewerManager.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ViewerManager(object):
    def setupUi(self, ViewerManager):
        ViewerManager.setObjectName(_fromUtf8("ViewerManager"))
        ViewerManager.resize(640, 480)
        self.centralwidget = QtGui.QWidget(ViewerManager)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.treeView_PlanetAttribute = QtGui.QTreeView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView_PlanetAttribute.sizePolicy().hasHeightForWidth())
        self.treeView_PlanetAttribute.setSizePolicy(sizePolicy)
        self.treeView_PlanetAttribute.setMinimumSize(QtCore.QSize(100, 200))
        self.treeView_PlanetAttribute.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.treeView_PlanetAttribute.setObjectName(_fromUtf8("treeView_PlanetAttribute"))
        self.horizontalLayout.addWidget(self.treeView_PlanetAttribute)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.radioButton_AutoRun = QtGui.QRadioButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_AutoRun.sizePolicy().hasHeightForWidth())
        self.radioButton_AutoRun.setSizePolicy(sizePolicy)
        self.radioButton_AutoRun.setObjectName(_fromUtf8("radioButton_AutoRun"))
        self.horizontalLayout_3.addWidget(self.radioButton_AutoRun)
        self.lineEdit_Start_Time = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Start_Time.sizePolicy().hasHeightForWidth())
        self.lineEdit_Start_Time.setSizePolicy(sizePolicy)
        self.lineEdit_Start_Time.setMaximumSize(QtCore.QSize(16777215, 16777215))
        #self.lineEdit_Start_Time.setClearButtonEnabled(False)
        self.lineEdit_Start_Time.setObjectName(_fromUtf8("lineEdit_Start_Time"))
        self.horizontalLayout_3.addWidget(self.lineEdit_Start_Time)
        self.label_to = QtGui.QLabel(self.centralwidget)
        self.label_to.setObjectName(_fromUtf8("label_to"))
        self.horizontalLayout_3.addWidget(self.label_to)
        self.lineEdit_EndTime = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_EndTime.sizePolicy().hasHeightForWidth())
        self.lineEdit_EndTime.setSizePolicy(sizePolicy)
        self.lineEdit_EndTime.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_EndTime.setObjectName(_fromUtf8("lineEdit_EndTime"))
        self.horizontalLayout_3.addWidget(self.lineEdit_EndTime)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEdit_RefreshRate = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_RefreshRate.sizePolicy().hasHeightForWidth())
        self.lineEdit_RefreshRate.setSizePolicy(sizePolicy)
        self.lineEdit_RefreshRate.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_RefreshRate.setObjectName(_fromUtf8("lineEdit_RefreshRate"))
        self.gridLayout.addWidget(self.lineEdit_RefreshRate, 0, 1, 1, 1)
        self.lineEdit_Time = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Time.sizePolicy().hasHeightForWidth())
        self.lineEdit_Time.setSizePolicy(sizePolicy)
        self.lineEdit_Time.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_Time.setObjectName(_fromUtf8("lineEdit_Time"))
        self.gridLayout.addWidget(self.lineEdit_Time, 1, 1, 1, 1)
        self.label_RefreshRate = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_RefreshRate.sizePolicy().hasHeightForWidth())
        self.label_RefreshRate.setSizePolicy(sizePolicy)
        self.label_RefreshRate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RefreshRate.setObjectName(_fromUtf8("label_RefreshRate"))
        self.gridLayout.addWidget(self.label_RefreshRate, 0, 0, 1, 1)
        self.label_Time = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Time.sizePolicy().hasHeightForWidth())
        self.label_Time.setSizePolicy(sizePolicy)
        self.label_Time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_Time.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Time.setObjectName(_fromUtf8("label_Time"))
        self.gridLayout.addWidget(self.label_Time, 1, 0, 1, 1)
        self.pushButton_showtime = QtGui.QPushButton(self.centralwidget)
        self.pushButton_showtime.setObjectName(_fromUtf8("pushButton_showtime"))
        self.gridLayout.addWidget(self.pushButton_showtime, 1, 2, 1, 1)
        self.pushButton_updaterate = QtGui.QPushButton(self.centralwidget)
        self.pushButton_updaterate.setObjectName(_fromUtf8("pushButton_updaterate"))
        self.gridLayout.addWidget(self.pushButton_updaterate, 0, 2, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        ViewerManager.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ViewerManager)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuKepler_VIewer = QtGui.QMenu(self.menubar)
        self.menuKepler_VIewer.setObjectName(_fromUtf8("menuKepler_VIewer"))
        self.menuFIle = QtGui.QMenu(self.menubar)
        self.menuFIle.setObjectName(_fromUtf8("menuFIle"))
        ViewerManager.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ViewerManager)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ViewerManager.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(ViewerManager)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_Image = QtGui.QAction(ViewerManager)
        self.actionSave_Image.setObjectName(_fromUtf8("actionSave_Image"))
        self.actionLoad = QtGui.QAction(ViewerManager)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionAbout_Kepler_Viewer = QtGui.QAction(ViewerManager)
        self.actionAbout_Kepler_Viewer.setObjectName(_fromUtf8("actionAbout_Kepler_Viewer"))
        self.menuKepler_VIewer.addAction(self.actionAbout_Kepler_Viewer)
        self.menuFIle.addAction(self.actionSave)
        self.menuFIle.addAction(self.actionSave_Image)
        self.menuFIle.addAction(self.actionLoad)
        self.menubar.addAction(self.menuKepler_VIewer.menuAction())
        self.menubar.addAction(self.menuFIle.menuAction())

        self.retranslateUi(ViewerManager)
        QtCore.QMetaObject.connectSlotsByName(ViewerManager)

    def retranslateUi(self, ViewerManager):
        ViewerManager.setWindowTitle(_translate("ViewerManager", "MainWindow", None))
        self.radioButton_AutoRun.setText(_translate("ViewerManager", "Run", None))
        self.label_to.setText(_translate("ViewerManager", "to", None))
        self.label_RefreshRate.setText(_translate("ViewerManager", "Refresh Rate:", None))
        self.label_Time.setText(_translate("ViewerManager", "Time:", None))
        self.pushButton_showtime.setText(_translate("ViewerManager", "show", None))
        self.pushButton_updaterate.setText(_translate("ViewerManager", "update", None))
        self.menuKepler_VIewer.setTitle(_translate("ViewerManager", "Kepler VIewer", None))
        self.menuFIle.setTitle(_translate("ViewerManager", "FIle", None))
        self.actionSave.setText(_translate("ViewerManager", "Save", None))
        self.actionSave_Image.setText(_translate("ViewerManager", "Save Image", None))
        self.actionLoad.setText(_translate("ViewerManager", "Load", None))
        self.actionAbout_Kepler_Viewer.setText(_translate("ViewerManager", "About Kepler Viewer", None))

